### ISSUE TITLE
Add periodic boundary conditions --- Neighbour detection

### ISSUE THREAD

**Issue by rasake** [fredrikm/SoCSProject16#14]
is_visible must fold the plane or something, maybe replicate game board as suggested by Giovanni?

**Comment by fredrikm** [comment]
This kind of works now but needs the updated sensor stuff to verify it (in an easy way)

**Comment by rasake** [comment]
Sensor stuff fix in branch 28-predator-bug, see pull request #30

**Comment by rasake** [comment]
Fixed by pull request #37
