### ISSUE TITLE
Main training loop

### ISSUE THREAD

**Issue by rasake** [fredrikm/SoCSProject16#17]
Make a main loop that optimizes ann weights. Run evaluations in parallel.

**Comment by fredrikm** [comment]
Separate rate this loop from presentation loop that uses graphics. We might even wan't a new main for training.

**Comment by rasake** [comment]
I'll take on this issue as soon as the new control/settings flow is merged, see #25

**Comment by fredrikm** [comment]
go ahead then! :)

**Comment by rasake** [comment]
Done
