### ISSUE TITLE
Simulation speed is very slow

### ISSUE THREAD

**Issue by reinthal** [fredrikm/SoCSProject16#52]
Evaluating the particles takes as a long time. 600 time steps is evaluated in 129 seconds

here is a screenshot
[elapsed time](http://imgur.com/a/AoWZ0)

**Comment by fredrikm** [comment]
We might be able to distribute the neighbour calculation over several timesteps (for ex. odd fish idx on odd timestep, even idx on even timesteps), but care must be taken when removing fishes so the neighbourlists doesn't contain invalid references.

**Comment by reinthal** [comment]
This bug resolved when shark started killing off the fish.
