### ISSUE TITLE
Add parallelization for evaluating particles/chromosomes

### ISSUE THREAD

**Issue by ghost** [fredrikm/SoCSProject16#57]

**Comment by reinthal** [comment]
Just thought about this also. Looking into how this can be done :)

**Comment by reinthal** [comment]
Looks like this is the stuff we want since its just a for loop that needs paralellizing

https://pythonhosted.org/joblib/parallel.html

**Comment by reinthal** [comment]
https://docs.python.org/2/library/multiprocessing.html
