### ISSUE TITLE
Add periodic boundary conditions --- Movement

### ISSUE THREAD

**Issue by rasake** [fredrikm/SoCSProject16#6]

**Comment by reinthal** [comment]
Jag fixar den här! Börjar äntligen fatta git :)

**Comment by rasake** [comment]
Gött mos. Den undre gränsen funkar dock inte om den är skild från noll. Vi kanske bara ska ta bort det alternativet helt?

**Comment by reinthal** [comment]
@rasake den undre gränsen känns lite onödig på det viset ja. Jag är ok med att ta bort den. Är du?

**Comment by rasake** [comment]
Kör i vind!

**Comment by rasake** [comment]
FIxa hajen också

**Comment by rasake** [comment]
Hajen fixad av merge 25
