### ISSUE TITLE
Generate presentation videos

### ISSUE THREAD

**Issue by rasake** [fredrikm/SoCSProject16#65]
Videos to display interesting behavior
- Moving towards other fish
- Avoiding shark
- Fish moving in line formation
- Swarm splitting and rejoining
- "bloopers", silly behaviors like circling the shark

**Comment by rasake** [comment]
- No ANN (to demonstrate collision avoidance)
- Random ANN (before training)?
- Other types of formation

**Comment by fredrikm** [comment]
Added a shared google drive folder where I put videos (invitations should be sent out).
- No shark, 2 fish groups "merging"
- No ANN, no shark just fish collision
- Random ANN, no shark
- Fish, shark avoidance
- Generational improvement videos, both with and without shark

https://drive.google.com/drive/folders/0B2e0T66f3yUxQjVscEw1eVpIVUU
